[package]
name = "list-sync"
version = "0.1.0"
authors = ["Mohammed Ajmal Siddiqui <ajmalsiddiqui21@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
